FROM node:24-bookworm-slim AS build
WORKDIR /build
RUN npm install --global npm@11.16.0
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /build/dist/todo-list/browser /usr/share/nginx/html
EXPOSE 80
