package com.example.todobackend.config;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

class DatabaseMigrationTest {
  @Test
  void upgradesLegacyDataWithoutClaimingAccountsOrLosingTasks() throws Exception {
    String url = "jdbc:h2:mem:legacy-upgrade;DB_CLOSE_DELAY=-1";
    try (var connection = DriverManager.getConnection(url, "sa", "");
        var sql = connection.createStatement()) {
      sql.execute(
          "CREATE TABLE app_user(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,username"
              + " VARCHAR(50) NOT NULL UNIQUE,created_at TIMESTAMP WITH TIME ZONE NOT NULL)");
      sql.execute(
          "CREATE TABLE todo(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT"
              + " NOT NULL REFERENCES app_user(id),description VARCHAR(255) NOT NULL,target_date"
              + " DATE NOT NULL,done BOOLEAN NOT NULL)");
      sql.execute("INSERT INTO app_user VALUES(1,'legacy',CURRENT_TIMESTAMP)");
      sql.execute("INSERT INTO todo VALUES(1,1,'Keep this task',DATE '2026-12-01',TRUE)");
    }
    var flyway =
        Flyway.configure()
            .dataSource(url, "sa", "")
            .baselineOnMigrate(true)
            .baselineVersion("1")
            .load();
    assertThat(flyway.migrate().migrationsExecuted).isEqualTo(3);
    assertThat(flyway.migrate().migrationsExecuted).isZero();
    try (var connection = DriverManager.getConnection(url, "sa", "");
        var sql = connection.createStatement()) {
      try (var rows =
          sql.executeQuery("SELECT username,password_hash,credential_version FROM app_user")) {
        assertThat(rows.next()).isTrue();
        assertThat(rows.getString(1)).isEqualTo("legacy");
        assertThat(rows.getString(2)).isNull();
        assertThat(rows.getLong(3)).isZero();
      }
      try (var rows =
          sql.executeQuery(
              "SELECT description,done,priority,completed_at,subtasks_json,recurrence_generated"
                  + " FROM todo")) {
        assertThat(rows.next()).isTrue();
        assertThat(rows.getString(1)).isEqualTo("Keep this task");
        assertThat(rows.getBoolean(2)).isTrue();
        assertThat(rows.getString(3)).isEqualTo("MEDIUM");
        assertThat(rows.getObject(4)).isNotNull();
        assertThat(rows.getString(5)).isEqualTo("[]");
        assertThat(rows.getBoolean(6)).isFalse();
      }
      sql.execute("UPDATE todo SET target_date=NULL WHERE id=1");
    }
  }
}
